services:
  - type: web
    name: seo-metrics-runner
    runtime: node
    plan: starter
    rootDir: services/seo-metrics-runner
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health 