#!/bin/bash
# Deploy Rust domain-runner to Render NOW

echo "🚀 RUST DOMAIN-RUNNER DEPLOYMENT"
echo "================================="
echo ""
echo "Your code is pushed to GitHub and ready to deploy!"
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "1. Click this link to deploy:"
echo "   👉 https://dashboard.render.com/select-repo?type=blueprint"
echo ""
echo "2. Select your repository:"
echo "   - Repository: beargallbladder/domain-runner"
echo "   - Branch: main"
echo "   - Blueprint file: render-rust.yaml"
echo ""
echo "3. Click 'Apply' to create services"
echo ""
echo "4. IMPORTANT: After services are created:"
echo "   a. Go to each service (web and worker)"
echo "   b. Click 'Environment' tab"
echo "   c. Update DATABASE_URL to your existing production database"
echo "   d. Add your LLM API keys (OPENAI_API_KEY, etc.)"
echo ""
echo "🔐 SAFETY NOTES:"
echo "- Services start in READ-ONLY mode (DB_READONLY=true)"
echo "- No data will be modified until you enable features"
echo "- All attempts are logged to rust_audit_log table"
echo ""
echo "📊 AFTER DEPLOYMENT (5-10 minutes):"
echo ""
echo "Run this to verify:"
echo "  ./check_deployment.sh"
echo ""
echo "You should see:"
echo "- Your real domain counts"
echo "- Your actual drift data"
echo "- db_readonly: true (safe mode)"
echo ""
echo "🎯 GRADUAL ROLLOUT:"
echo ""
echo "Once verified, use:"
echo "  ./enable_production.sh"
echo ""
echo "To gradually enable features:"
echo "- Phase 1: Drift writes only"
echo "- Phase 2: Worker writes"
echo "- Phase 3: Cron jobs"
echo "- Phase 4: Full production"
echo ""
echo "Press Enter to open Render Dashboard..."
read

# Open Render dashboard
if command -v open &> /dev/null; then
    open "https://dashboard.render.com/select-repo?type=blueprint"
elif command -v xdg-open &> /dev/null; then
    xdg-open "https://dashboard.render.com/select-repo?type=blueprint"
else
    echo "Please open: https://dashboard.render.com/select-repo?type=blueprint"
fi