services:
  - type: web
    name: raw-capture-runner
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: raw-capture-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false

databases:
  - name: raw-capture-db
    plan: starter
    ipAllowList: [] 