# Render deployment configuration
databases:
  - name: domain-runner-db
    plan: free
    databaseName: domain_runner
    user: nexus

services:
  # Web API Service
  - type: web
    name: domain-runner-web
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: domain-runner-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: AI21_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false

  # Background Worker Service
  - type: worker
    name: domain-runner-worker
    env: docker
    plan: starter
    autoDeploy: true
    dockerCommand: python -m src.worker
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: NODE_ENV
        value: production
      - key: WORKER_INTERVAL_SEC
        value: "300"
      - key: WORKER_BATCH_SIZE
        value: "10"
      - key: ENABLE_DRIFT_MONITORING
        value: "true"
      - key: ENABLE_TENSOR_PROCESSING
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: domain-runner-db
          property: connectionString
      - fromGroup: llm-api-keys

# Optional: Cron job for scheduled crawls
# Uncomment when ready to enable
# - type: cron
#   name: domain-runner-hourly-crawl
#   env: docker
#   plan: starter
#   schedule: "0 * * * *"  # Every hour
#   dockerCommand: python -m src.worker run_once
#   envVars:
#     - key: NODE_ENV
#       value: production
#     - key: DATABASE_URL
#       fromDatabase:
#         name: domain-runner-db
#         property: connectionString
#     - fromGroup: llm-api-keys