services:
  - type: web
    name: raw-capture-runner
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: raw-capture-db
          property: connectionString

databases:
  - name: raw-capture-db
    plan: starter 