services:
  - type: web
    name: raw-capture-runner
    runtime: node
    buildCommand: npm cache clean --force && npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CACHE_BUST
        value: "2025_06_09_06_02_FORCE_REBUILD"
      - key: BUILD_ID
        value: "ULTRA_NUCLEAR_565_DOMAINS"
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: raw-capture-db
          property: connectionString

databases:
  - name: raw-capture-db
    plan: basic-1gb 