services:
  - type: web
    name: embedding-engine
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python embedding_runner.py"
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: ENVIRONMENT
        value: production
      # READ REPLICA CONFIGURATION
      # Option 1: If you have a read replica, use its URL here
      - key: READ_REPLICA_URL
        fromService:
          type: pserv
          name: raw-capture-db-replica  # Your read replica service name
          property: connectionString
      # Option 2: If no read replica, this will fallback to main database
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: raw-capture-db  # Your main database service name
          property: connectionString 