services:
  - type: web
    name: embedding-engine
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python embedding_runner.py"
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      # Database configuration using direct URLs
      - key: READ_REPLICA_URL
        value: "postgresql://raw_capture_db_user:wjFesUM8ISNEvE2b4kZtRAKgGYJVtKK5@dpg-d11fqgndiees73fb35dg-b/raw_capture_db"
      - key: DATABASE_URL
        value: "postgresql://raw_capture_db_user:wjFesUM8ISNEvE2b4kZtRAKgGYJVtKK5@dpg-d11fqgndiees73fb35dg-a.oregon-postgres.render.com/raw_capture_db" 