services:
  - type: web
    name: memory-oracle-tensor
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        fromDatabase:
          name: raw-capture-db
          property: connectionString
      - key: TENSOR_COMPUTE_INTERVAL
        value: 60
      - key: DRIFT_DETECTION_INTERVAL
        value: 120
      - key: CONSENSUS_COMPUTE_INTERVAL
        value: 90

databases:
  - name: raw-capture-db
    plan: starter
    region: oregon