services:
  - type: web
    name: predictive-analytics
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: raw_capture_db
          property: connectionString
      - key: LOG_LEVEL
        value: info
      - key: SERVICE_NAME
        value: predictive-analytics
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - services/predictive-analytics/**
    headers:
      - path: /api/*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /api/*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /api/*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, X-Requested-With"