services:
  - type: web
    name: visceral-intelligence
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    region: oregon
    plan: starter
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: raw_capture_db
          property: connectionString
      - key: SERVICE_NAME
        value: visceral-intelligence
      - key: INTERNAL_API_KEY
        generateValue: true
      - key: ADMIN_API_KEY
        generateValue: true