services:
  # Main Enterprise Neural Gateway Service
  - type: web
    name: enterprise-neural-gateway
    env: node
    region: oregon
    plan: standard
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/v2/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: REDIS_URL
        value: redis://red-d11m4andiees73fbmg10:6379
      - key: DATABASE_URL
        value: postgresql://raw_capture_db_user:wjFesUM8ISNEvE2b4kZtRAKgGYJVtKK5@dpg-d11fqgndiees73fb35dg-a.oregon-postgres.render.com/raw_capture_db
      # Partner & Premium Keys
      - key: PAGERANK_API_KEY
        value: llmpagerank-2025-neural-gateway
      - key: BRANDSENTIMENT_API_KEY
        value: brandsentiment-premium-2025
      - key: ENTERPRISE_API_KEY
        value: enterprise-tier-2025-secure
      # Closed-Loop Configuration
      - key: JUICE_WEIGHT
        value: "0.6"
      - key: DECAY_WEIGHT
        value: "0.3"
      - key: SLA_WEIGHT
        value: "0.1"
      - key: ENABLE_WEBSOCKET
        value: "true"
      - key: WS_PATH
        value: /ws/realtime
      # Import existing API keys from group
      - fromGroup: domain-runner-secrets