#!/bin/bash

echo "🎯 COHORT INTELLIGENCE - RENDER DEPLOYMENT GUIDE"
echo "================================================"
echo ""
echo "✅ Code committed and pushed to GitHub!"
echo ""
echo "🚀 NEXT STEPS - Deploy to Render:"
echo ""
echo "1. Go to https://dashboard.render.com/"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repo: beargallbladder/domain-runner"
echo "4. Configure the service:"
echo "   - Name: cohort-intelligence-service"
echo "   - Root Directory: services/cohort-intelligence"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Instance Type: Starter (Free)"
echo ""
echo "5. Add Environment Variables:"
echo "   - DATABASE_URL: postgresql://raw_capture_db_user:wjFesUM8ISNEvE2b4kZtRAKgGYJVtKK5@dpg-d11fqgndiees73fb35dg-a.oregon-postgres.render.com/raw_capture_db"
echo "   - OPENAI_API_KEY: [Your OpenAI API Key]"
echo "   - NODE_ENV: production"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "🎯 Expected Result:"
echo "   Service URL: https://cohort-intelligence-service.onrender.com"
echo "   Health Check: https://cohort-intelligence-service.onrender.com/"
echo ""
echo "💡 The service will automatically:"
echo "   - Create database tables (domain_categories, category_competitors, cohort_rankings)"
echo "   - Connect to your existing production database"
echo "   - Provide 5 API endpoints for cohort intelligence"
echo ""
echo "🔥 NO MORE LOCAL DATABASE LOOPS!"
echo "🔥 PRODUCTION ENVIRONMENT VARIABLES WORK!"
echo "🔥 READY FOR COHORT INTELLIGENCE!" 