services:
  - type: worker
    name: rust-crawler
    runtime: docker
    dockerfilePath: ./rust/Dockerfile
    dockerContext: ./rust
    region: oregon
    plan: standard
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: raw_capture_db
          property: connectionString
      - key: RUST_LOG
        value: info
      - key: GLOBAL_CONCURRENCY
        value: 64
      - key: CRAWL_SLA_TARGET_SECS
        value: 3600
      - key: CRAWL_SLA_MAX_SECS
        value: 7200
      - key: PROVIDER_TIMEOUT_MS
        value: 15000
      - key: COST_BUDGET_USD
        value: 150
      # API keys are already configured on Render