name: On Spec Change
on:
  push:
    paths:
      - 'sentinel/specs/**.md'
      - 'sentinel/orchestration/**.yml'
      - 'sentinel/interfaces/**.json'
jobs:
  validate-and-dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          cd sentinel
          npm ci --prefix services/runner-node || echo "Node deps not ready yet"
          pip install -r scripts/requirements.txt
      
      - name: Validate PRD invariants
        run: |
          cd sentinel
          python scripts/propose_spec_update.py --validate --spec specs/sentinel.prd.md
      
      - name: Validate JSON schemas
        run: |
          cd sentinel
          python -m jsonschema interfaces/job.schema.json --version
          python -m jsonschema interfaces/artifact.schema.json --version
          python -m jsonschema interfaces/run.schema.json --version
      
      - name: RuvNet dry-run plan
        env:
          # Pull from Render instead of GitHub secrets
          RENDER_SERVICE_URL: ${{ vars.RENDER_SERVICE_URL }}
        run: |
          cd sentinel
          export RUN_ID=dryrun-${{ github.run_id }}
          # If ruvnet CLI is available
          which ruvnet && ruvnet run orchestration/ruvnet/hive.yml --dry-run --run-id $RUN_ID || echo "RuvNet CLI not installed, skipping dry-run"